input_lvs = [
    {
        'X': (0, 1.01, 0.01),
        'name': 'Area',
        'terms': {
            'minimal': ('trapmf', 0, 0, 0.2, 0.3),
            'modest': ('trapmf', 0.2, 0.3, 0.4, 0.6),
            'comfortable': ('trimf', 0.4, 0.55, 0.7),
            'spacious': ('trapmf', 0.6, 0.7, 1, 1),
        }
    },

    {
        'X': (0, 1.01, 0.01),
        'name': 'Floor',
        'terms': {
            'lower': ('trapmf', 0, 0, 0.2, 0.4),
            'middle': ('trapmf', 0.25, 0.4, 0.6, 0.75),
            'upper': ('trapmf', 0.6, 0.8, 1, 1),
        }
    },

    {
        'X': (0, 1.01, 0.01),
        'name': 'Сondition',
        'terms': {
            'new': ('trapmf', 0.7, 0.9, 1, 1),
            'in good condition': ('trapmf', 0.4, 0.5, 0.7, 0.9),
            'needs repair': ('trapmf', 0, 0, 0.4, 0.6),
        }
    },

    {
        'X': (0, 1.01, 0.01),
        'name': 'Distance to the city center',
        'terms': {
            'in the center': ('trapmf', 0, 0, 0.15, 0.25),
            'near the center': ('trimf', 0.15, 0.25, 0.35),
            'far from the center': ('trimf', 0.25, 0.5, 0.75),
            'on the outskirts': ('trapmf', 0.5, 0.75, 1, 1),
        }
    }
]

output_lv = {
    'X': (0, 1.01, 0.01),
    'name': 'Class',
    'terms': {
        'budget': ('trapmf', 0, 0, 0.1, 0.2),
        'economical': ('trimf', 0.1, 0.2, 0.35),
        'average price': ('trapmf', 0.2, 0.3, 0.4, 0.5),
        'moderately expensive': ('trimf', 0.4, 0.55, 0.7),
        'expensive': ('trapmf', 0.6, 0.7, 0.8, 0.9),
        'luxurious': ('trapmf', 0.8, 0.95, 1, 1),
    }
}


rule_base = [
	(('minimal', 'lower', 'new', 'in the center'), 'moderately expensive'),
	(('minimal', 'lower', 'new', 'near the center'), 'moderately expensive'),
	(('minimal', 'lower', 'new', 'far from the center'), 'average price'),
	(('minimal', 'lower', 'new', 'on the outskirts'), 'average price'),
	(('minimal', 'lower', 'in good condition', 'in the center'), 'average price'),
	(('minimal', 'lower', 'in good condition', 'near the center'), 'average price'),
	(('minimal', 'lower', 'in good condition', 'far from the center'), 'economical'),
	(('minimal', 'lower', 'in good condition', 'on the outskirts'), 'economical'),
	(('minimal', 'lower', 'needs repair', 'in the center'), 'economical'),
	(('minimal', 'lower', 'needs repair', 'near the center'), 'budget'),
	(('minimal', 'lower', 'needs repair', 'far from the center'), 'budget'),
	(('minimal', 'lower', 'needs repair', 'on the outskirts'), 'budget'),
	(('minimal', 'middle', 'new', 'in the center'), 'moderately expensive'),
	(('minimal', 'middle', 'new', 'near the center'), 'moderately expensive'),
	(('minimal', 'middle', 'new', 'far from the center'), 'moderately expensive'),
	(('minimal', 'middle', 'new', 'on the outskirts'), 'average price'),
	(('minimal', 'middle', 'in good condition', 'in the center'), 'average price'),
	(('minimal', 'middle', 'in good condition', 'near the center'), 'average price'),
	(('minimal', 'middle', 'in good condition', 'far from the center'), 'average price'),
	(('minimal', 'middle', 'in good condition', 'on the outskirts'), 'economical'),
	(('minimal', 'middle', 'needs repair', 'in the center'), 'economical'),
	(('minimal', 'middle', 'needs repair', 'near the center'), 'budget'),
	(('minimal', 'middle', 'needs repair', 'far from the center'), 'budget'),
	(('minimal', 'middle', 'needs repair', 'on the outskirts'), 'budget'),
	(('minimal', 'upper', 'new', 'in the center'), 'moderately expensive'),
	(('minimal', 'upper', 'new', 'near the center'), 'moderately expensive'),
	(('minimal', 'upper', 'new', 'far from the center'), 'moderately expensive'),
	(('minimal', 'upper', 'new', 'on the outskirts'), 'moderately expensive'),
	(('minimal', 'upper', 'in good condition', 'in the center'), 'moderately expensive'),
	(('minimal', 'upper', 'in good condition', 'near the center'), 'average price'),
	(('minimal', 'upper', 'in good condition', 'far from the center'), 'average price'),
	(('minimal', 'upper', 'in good condition', 'on the outskirts'), 'average price'),
	(('minimal', 'upper', 'needs repair', 'in the center'), 'average price'),
	(('minimal', 'upper', 'needs repair', 'near the center'), 'economical'),
	(('minimal', 'upper', 'needs repair', 'far from the center'), 'budget'),
	(('minimal', 'upper', 'needs repair', 'on the outskirts'), 'budget'),
	(('modest', 'lower', 'new', 'in the center'), 'moderately expensive'),
	(('modest', 'lower', 'new', 'near the center'), 'moderately expensive'),
	(('modest', 'lower', 'new', 'far from the center'), 'moderately expensive'),
	(('modest', 'lower', 'new', 'on the outskirts'), 'moderately expensive'),
	(('modest', 'lower', 'in good condition', 'in the center'), 'moderately expensive'),
	(('modest', 'lower', 'in good condition', 'near the center'), 'moderately expensive'),
	(('modest', 'lower', 'in good condition', 'far from the center'), 'average price'),
	(('modest', 'lower', 'in good condition', 'on the outskirts'), 'average price'),
	(('modest', 'lower', 'needs repair', 'in the center'), 'average price'),
	(('modest', 'lower', 'needs repair', 'near the center'), 'economical'),
	(('modest', 'lower', 'needs repair', 'far from the center'), 'economical'),
	(('modest', 'lower', 'needs repair', 'on the outskirts'), 'budget'),
	(('modest', 'middle', 'new', 'in the center'), 'expensive'),
	(('modest', 'middle', 'new', 'near the center'), 'moderately expensive'),
	(('modest', 'middle', 'new', 'far from the center'), 'moderately expensive'),
	(('modest', 'middle', 'new', 'on the outskirts'), 'moderately expensive'),
	(('modest', 'middle', 'in good condition', 'in the center'), 'moderately expensive'),
	(('modest', 'middle', 'in good condition', 'near the center'), 'moderately expensive'),
	(('modest', 'middle', 'in good condition', 'far from the center'), 'moderately expensive'),
	(('modest', 'middle', 'in good condition', 'on the outskirts'), 'average price'),
	(('modest', 'middle', 'needs repair', 'in the center'), 'average price'),
	(('modest', 'middle', 'needs repair', 'near the center'), 'average price'),
	(('modest', 'middle', 'needs repair', 'far from the center'), 'economical'),
	(('modest', 'middle', 'needs repair', 'on the outskirts'), 'economical'),
	(('modest', 'upper', 'new', 'in the center'), 'expensive'),
	(('modest', 'upper', 'new', 'near the center'), 'expensive'),
	(('modest', 'upper', 'new', 'far from the center'), 'moderately expensive'),
	(('modest', 'upper', 'new', 'on the outskirts'), 'moderately expensive'),
	(('modest', 'upper', 'in good condition', 'in the center'), 'moderately expensive'),
	(('modest', 'upper', 'in good condition', 'near the center'), 'moderately expensive'),
	(('modest', 'upper', 'in good condition', 'far from the center'), 'moderately expensive'),
	(('modest', 'upper', 'in good condition', 'on the outskirts'), 'moderately expensive'),
	(('modest', 'upper', 'needs repair', 'in the center'), 'average price'),
	(('modest', 'upper', 'needs repair', 'near the center'), 'average price'),
	(('modest', 'upper', 'needs repair', 'far from the center'), 'average price'),
	(('modest', 'upper', 'needs repair', 'on the outskirts'), 'economical'),
	(('comfortable', 'lower', 'new', 'in the center'), 'expensive'),
	(('comfortable', 'lower', 'new', 'near the center'), 'expensive'),
	(('comfortable', 'lower', 'new', 'far from the center'), 'expensive'),
	(('comfortable', 'lower', 'new', 'on the outskirts'), 'moderately expensive'),
	(('comfortable', 'lower', 'in good condition', 'in the center'), 'moderately expensive'),
	(('comfortable', 'lower', 'in good condition', 'near the center'), 'moderately expensive'),
	(('comfortable', 'lower', 'in good condition', 'far from the center'), 'moderately expensive'),
	(('comfortable', 'lower', 'in good condition', 'on the outskirts'), 'moderately expensive'),
	(('comfortable', 'lower', 'needs repair', 'in the center'), 'moderately expensive'),
	(('comfortable', 'lower', 'needs repair', 'near the center'), 'average price'),
	(('comfortable', 'lower', 'needs repair', 'far from the center'), 'average price'),
	(('comfortable', 'lower', 'needs repair', 'on the outskirts'), 'average price'),
	(('comfortable', 'middle', 'new', 'in the center'), 'expensive'),
	(('comfortable', 'middle', 'new', 'near the center'), 'expensive'),
	(('comfortable', 'middle', 'new', 'far from the center'), 'expensive'),
	(('comfortable', 'middle', 'new', 'on the outskirts'), 'expensive'),
	(('comfortable', 'middle', 'in good condition', 'in the center'), 'moderately expensive'),
	(('comfortable', 'middle', 'in good condition', 'near the center'), 'moderately expensive'),
	(('comfortable', 'middle', 'in good condition', 'far from the center'), 'moderately expensive'),
	(('comfortable', 'middle', 'in good condition', 'on the outskirts'), 'moderately expensive'),
	(('comfortable', 'middle', 'needs repair', 'in the center'), 'moderately expensive'),
	(('comfortable', 'middle', 'needs repair', 'near the center'), 'moderately expensive'),
	(('comfortable', 'middle', 'needs repair', 'far from the center'), 'average price'),
	(('comfortable', 'middle', 'needs repair', 'on the outskirts'), 'average price'),
	(('comfortable', 'upper', 'new', 'in the center'), 'luxurious'),
	(('comfortable', 'upper', 'new', 'near the center'), 'expensive'),
	(('comfortable', 'upper', 'new', 'far from the center'), 'expensive'),
	(('comfortable', 'upper', 'new', 'on the outskirts'), 'expensive'),
	(('comfortable', 'upper', 'in good condition', 'in the center'), 'expensive'),
	(('comfortable', 'upper', 'in good condition', 'near the center'), 'moderately expensive'),
	(('comfortable', 'upper', 'in good condition', 'far from the center'), 'moderately expensive'),
	(('comfortable', 'upper', 'in good condition', 'on the outskirts'), 'moderately expensive'),
	(('comfortable', 'upper', 'needs repair', 'in the center'), 'moderately expensive'),
	(('comfortable', 'upper', 'needs repair', 'near the center'), 'moderately expensive'),
	(('comfortable', 'upper', 'needs repair', 'far from the center'), 'moderately expensive'),
	(('comfortable', 'upper', 'needs repair', 'on the outskirts'), 'average price'),
	(('spacious', 'lower', 'new', 'in the center'), 'luxurious'),
	(('spacious', 'lower', 'new', 'near the center'), 'expensive'),
	(('spacious', 'lower', 'new', 'far from the center'), 'expensive'),
	(('spacious', 'lower', 'new', 'on the outskirts'), 'expensive'),
	(('spacious', 'lower', 'in good condition', 'in the center'), 'expensive'),
	(('spacious', 'lower', 'in good condition', 'near the center'), 'expensive'),
	(('spacious', 'lower', 'in good condition', 'far from the center'), 'moderately expensive'),
	(('spacious', 'lower', 'in good condition', 'on the outskirts'), 'moderately expensive'),
	(('spacious', 'lower', 'needs repair', 'in the center'), 'moderately expensive'),
	(('spacious', 'lower', 'needs repair', 'near the center'), 'moderately expensive'),
	(('spacious', 'lower', 'needs repair', 'far from the center'), 'moderately expensive'),
	(('spacious', 'lower', 'needs repair', 'on the outskirts'), 'moderately expensive'),
	(('spacious', 'middle', 'new', 'in the center'), 'luxurious'),
	(('spacious', 'middle', 'new', 'near the center'), 'luxurious'),
	(('spacious', 'middle', 'new', 'far from the center'), 'expensive'),
	(('spacious', 'middle', 'new', 'on the outskirts'), 'expensive'),
	(('spacious', 'middle', 'in good condition', 'in the center'), 'expensive'),
	(('spacious', 'middle', 'in good condition', 'near the center'), 'expensive'),
	(('spacious', 'middle', 'in good condition', 'far from the center'), 'expensive'),
	(('spacious', 'middle', 'in good condition', 'on the outskirts'), 'moderately expensive'),
	(('spacious', 'middle', 'needs repair', 'in the center'), 'moderately expensive'),
	(('spacious', 'middle', 'needs repair', 'near the center'), 'moderately expensive'),
	(('spacious', 'middle', 'needs repair', 'far from the center'), 'moderately expensive'),
	(('spacious', 'middle', 'needs repair', 'on the outskirts'), 'moderately expensive'),
	(('spacious', 'upper', 'new', 'in the center'), 'luxurious'),
	(('spacious', 'upper', 'new', 'near the center'), 'luxurious'),
	(('spacious', 'upper', 'new', 'far from the center'), 'luxurious'),
	(('spacious', 'upper', 'new', 'on the outskirts'), 'luxurious'),
	(('spacious', 'upper', 'in good condition', 'in the center'), 'expensive'),
	(('spacious', 'upper', 'in good condition', 'near the center'), 'expensive'),
	(('spacious', 'upper', 'in good condition', 'far from the center'), 'expensive'),
	(('spacious', 'upper', 'in good condition', 'on the outskirts'), 'expensive'),
	(('spacious', 'upper', 'needs repair', 'in the center'), 'expensive'),
	(('spacious', 'upper', 'needs repair', 'near the center'), 'moderately expensive'),
	(('spacious', 'upper', 'needs repair', 'far from the center'), 'moderately expensive'),
	(('spacious', 'upper', 'needs repair', 'on the outskirts'), 'moderately expensive'),
]