input_lvs = [
    {
        'X': (0, 10.01, 0.01),
        'name': 'Area',
		'terms': {
			'Very small': {'umf': ('trapmf', 0, 0, 0.55, 4.61), 'lmf': ('trapmf', 0, 0, 0.09, 1.15, 1)},
			'Small': {'umf': ('trapmf', 0.42, 2.25, 4., 5.41), 'lmf': ('trapmf', 2.79, 3.21, 3.21, 3.71, 0.34)},
			'Average': {'umf': ('trapmf', 1.59, 2.75, 4.35, 6.26), 'lmf': ('trapmf', 2.79, 3.34, 3.34, 3.67, 0.35)},
			'Large': {'umf': ('trapmf', 3.38, 5.5, 7.25, 9.02), 'lmf': ('trapmf', 5.79, 6.28, 6.28, 6.67, 0.33)},
			'Very large': {'umf': ('trapmf', 4.59, 5.9, 7.25, 8.5), 'lmf': ('trapmf', 6.29, 6.67, 6.67, 7.17, 0.39)},
			'Extra large': {'umf': ('trapmf', 7.37, 9.36, 10, 10), 'lmf': ('trapmf', 8.68, 9.91, 10, 10, 1)},
		}
    },

    {
        'X': (0, 10.01, 0.01),
        'name': 'Floor',
        'terms': {
            'Lower': {'umf': ('trapmf', 0, 0, 0.55, 4.61), 'lmf': ('trapmf', 0, 0, 0.09, 1.15, 1)},
            'Below middle': {'umf': ('trapmf', 0.42, 2.25, 4.00, 5.41), 'lmf': ('trapmf', 2.79, 3.21, 3.21, 0.34, 3.71)},
            'Above middle': {'umf': ('trapmf', 3.38, 5.50, 7.25, 9.02), 'lmf': ('trapmf', 5.79, 6.28, 6.28, 0.33, 6.67)},
            'Upper': {'umf': ('trapmf', 7.37, 9.36, 10, 10), 'lmf': ('trapmf', 8.68, 9.91, 10, 10, 1)},
        }
    },

    {
        'X': (0, 10.01, 0.01),
        'name': 'Сondition',
		'terms': {
			'Very poor': {'umf': ('trapmf', 0, 0, 0.55, 4.61), 'lmf': ('trapmf', 0, 0, 0.09, 1.15, 1)},
			'Poor': {'umf': ('trapmf', 0.42, 2.25, 4., 5.41), 'lmf': ('trapmf', 2.79, 3.21, 3.21, 3.71, 0.34)},
			'Average': {'umf': ('trapmf', 1.59, 2.75, 4.35, 6.26), 'lmf': ('trapmf', 2.79, 3.34, 3.34, 3.67, 0.35)},
			'Good': {'umf': ('trapmf', 3.38, 5.5, 7.25, 9.02), 'lmf': ('trapmf', 5.79, 6.28, 6.28, 6.67, 0.33)},
			'Very good': {'umf': ('trapmf', 4.59, 5.9, 7.25, 8.5), 'lmf': ('trapmf', 6.29, 6.67, 6.67, 7.17, 0.39)},
			'Excellent': {'umf': ('trapmf', 7.37, 9.36, 10, 10), 'lmf': ('trapmf', 8.68, 9.91, 10, 10, 1)},
		}
    },

    {
        'X': (0, 10.01, 0.01),
        'name': 'Distance to the city center',
        'terms': {
            'in the center': {'umf': ('trapmf', 0, 0, 0.55, 4.61), 'lmf': ('trapmf', 0, 0, 0.09, 1.15, 1)},
            'near the center': {'umf': ('trapmf', 0.42, 2.25, 4.00, 5.41), 'lmf': ('trapmf', 2.79, 3.21, 3.21, 0.34, 3.71)},
            'far from the center': {'umf': ('trapmf', 3.38, 5.50, 7.25, 9.02), 'lmf': ('trapmf', 5.79, 6.28, 6.28, 0.33, 6.67)},
            'on the outskirts': {'umf': ('trapmf', 7.37, 9.36, 10, 10), 'lmf': ('trapmf', 8.68, 9.91, 10, 10, 1)},
        }
    }
]

output_lv = {
    'X': (0, 10.01, 0.01),
    'name': 'Class',
    'terms': {
        'Very low': {'umf': ('trapmf', 0, 0, 0.59, 3.95), 'lmf': ('trapmf', 0, 0, 0.09, 1.32, 1)},
        'Low': {'umf': ('trapmf', 0.28, 2.00, 3.00, 5.22), 'lmf': ('trapmf', 1.79, 2.37, 2.37, 2.71, 0.48)},
        'Favorable': {'umf': ('trapmf', 0.98, 2.75, 4.00, 5.41), 'lmf': ('trapmf', 2.79, 3.30, 3.30, 3.71, 0.42)},
        'Average': {'umf': ('trapmf', 2.38, 4.50, 6.00, 8.18), 'lmf': ('trapmf', 4.79, 5.12, 5.12, 5.35, 0.27)},
        'High': {'umf': ('trapmf', 4.02, 5.65, 7.00, 8.41), 'lmf': ('trapmf', 5.89, 6.34, 6.34, 6.81, 0.40)},
        'Very high': {'umf': ('trapmf', 4.38, 6.50, 7.75, 9.62), 'lmf': ('trapmf', 6.79, 7.25, 7.25, 7.91, 0.47)},
        'Extremely high': {'umf': ('trapmf', 5.21, 8.27, 10, 10), 'lmf': ('trapmf', 7.66, 9.82, 10, 10, 1)},
    }
}

rule_base = [
	(('Very small', 'Lower', 'Very poor', 'in the center'), 'Very low'),
	(('Very small', 'Lower', 'Very poor', 'near the center'), 'Very low'),
	(('Very small', 'Lower', 'Very poor', 'far from the center'), 'Very low'),
	(('Very small', 'Lower', 'Very poor', 'on the outskirts'), 'Very low'),
	(('Very small', 'Lower', 'Poor', 'in the center'), 'Very low'),
	(('Very small', 'Lower', 'Poor', 'near the center'), 'Very low'),
	(('Very small', 'Lower', 'Poor', 'far from the center'), 'Very low'),
	(('Very small', 'Lower', 'Poor', 'on the outskirts'), 'Very low'),
	(('Very small', 'Lower', 'Average', 'in the center'), 'Low'),
	(('Very small', 'Lower', 'Average', 'near the center'), 'Very low'),
	(('Very small', 'Lower', 'Average', 'far from the center'), 'Very low'),
	(('Very small', 'Lower', 'Average', 'on the outskirts'), 'Very low'),
	(('Very small', 'Lower', 'Good', 'in the center'), 'Low'),
	(('Very small', 'Lower', 'Good', 'near the center'), 'Low'),
	(('Very small', 'Lower', 'Good', 'far from the center'), 'Very low'),
	(('Very small', 'Lower', 'Good', 'on the outskirts'), 'Very low'),
	(('Very small', 'Lower', 'Very good', 'in the center'), 'Favorable'),
	(('Very small', 'Lower', 'Very good', 'near the center'), 'Favorable'),
	(('Very small', 'Lower', 'Very good', 'far from the center'), 'Low'),
	(('Very small', 'Lower', 'Very good', 'on the outskirts'), 'Low'),
	(('Very small', 'Lower', 'Excellent', 'in the center'), 'Average'),
	(('Very small', 'Lower', 'Excellent', 'near the center'), 'Favorable'),
	(('Very small', 'Lower', 'Excellent', 'far from the center'), 'Favorable'),
	(('Very small', 'Lower', 'Excellent', 'on the outskirts'), 'Low'),
	(('Very small', 'Below middle', 'Very poor', 'in the center'), 'Very low'),
	(('Very small', 'Below middle', 'Very poor', 'near the center'), 'Very low'),
	(('Very small', 'Below middle', 'Very poor', 'far from the center'), 'Very low'),
	(('Very small', 'Below middle', 'Very poor', 'on the outskirts'), 'Very low'),
	(('Very small', 'Below middle', 'Poor', 'in the center'), 'Very low'),
	(('Very small', 'Below middle', 'Poor', 'near the center'), 'Very low'),
	(('Very small', 'Below middle', 'Poor', 'far from the center'), 'Very low'),
	(('Very small', 'Below middle', 'Poor', 'on the outskirts'), 'Very low'),
	(('Very small', 'Below middle', 'Average', 'in the center'), 'Low'),
	(('Very small', 'Below middle', 'Average', 'near the center'), 'Low'),
	(('Very small', 'Below middle', 'Average', 'far from the center'), 'Very low'),
	(('Very small', 'Below middle', 'Average', 'on the outskirts'), 'Very low'),
	(('Very small', 'Below middle', 'Good', 'in the center'), 'Favorable'),
	(('Very small', 'Below middle', 'Good', 'near the center'), 'Low'),
	(('Very small', 'Below middle', 'Good', 'far from the center'), 'Low'),
	(('Very small', 'Below middle', 'Good', 'on the outskirts'), 'Very low'),
	(('Very small', 'Below middle', 'Very good', 'in the center'), 'Average'),
	(('Very small', 'Below middle', 'Very good', 'near the center'), 'Favorable'),
	(('Very small', 'Below middle', 'Very good', 'far from the center'), 'Low'),
	(('Very small', 'Below middle', 'Very good', 'on the outskirts'), 'Low'),
	(('Very small', 'Below middle', 'Excellent', 'in the center'), 'Average'),
	(('Very small', 'Below middle', 'Excellent', 'near the center'), 'Average'),
	(('Very small', 'Below middle', 'Excellent', 'far from the center'), 'Favorable'),
	(('Very small', 'Below middle', 'Excellent', 'on the outskirts'), 'Favorable'),
	(('Very small', 'Above middle', 'Very poor', 'in the center'), 'Very low'),
	(('Very small', 'Above middle', 'Very poor', 'near the center'), 'Very low'),
	(('Very small', 'Above middle', 'Very poor', 'far from the center'), 'Very low'),
	(('Very small', 'Above middle', 'Very poor', 'on the outskirts'), 'Very low'),
	(('Very small', 'Above middle', 'Poor', 'in the center'), 'Low'),
	(('Very small', 'Above middle', 'Poor', 'near the center'), 'Very low'),
	(('Very small', 'Above middle', 'Poor', 'far from the center'), 'Very low'),
	(('Very small', 'Above middle', 'Poor', 'on the outskirts'), 'Very low'),
	(('Very small', 'Above middle', 'Average', 'in the center'), 'Low'),
	(('Very small', 'Above middle', 'Average', 'near the center'), 'Low'),
	(('Very small', 'Above middle', 'Average', 'far from the center'), 'Very low'),
	(('Very small', 'Above middle', 'Average', 'on the outskirts'), 'Very low'),
	(('Very small', 'Above middle', 'Good', 'in the center'), 'Favorable'),
	(('Very small', 'Above middle', 'Good', 'near the center'), 'Low'),
	(('Very small', 'Above middle', 'Good', 'far from the center'), 'Low'),
	(('Very small', 'Above middle', 'Good', 'on the outskirts'), 'Low'),
	(('Very small', 'Above middle', 'Very good', 'in the center'), 'Average'),
	(('Very small', 'Above middle', 'Very good', 'near the center'), 'Favorable'),
	(('Very small', 'Above middle', 'Very good', 'far from the center'), 'Favorable'),
	(('Very small', 'Above middle', 'Very good', 'on the outskirts'), 'Low'),
	(('Very small', 'Above middle', 'Excellent', 'in the center'), 'High'),
	(('Very small', 'Above middle', 'Excellent', 'near the center'), 'Average'),
	(('Very small', 'Above middle', 'Excellent', 'far from the center'), 'Average'),
	(('Very small', 'Above middle', 'Excellent', 'on the outskirts'), 'Favorable'),
	(('Very small', 'Upper', 'Very poor', 'in the center'), 'Very low'),
	(('Very small', 'Upper', 'Very poor', 'near the center'), 'Very low'),
	(('Very small', 'Upper', 'Very poor', 'far from the center'), 'Very low'),
	(('Very small', 'Upper', 'Very poor', 'on the outskirts'), 'Very low'),
	(('Very small', 'Upper', 'Poor', 'in the center'), 'Low'),
	(('Very small', 'Upper', 'Poor', 'near the center'), 'Very low'),
	(('Very small', 'Upper', 'Poor', 'far from the center'), 'Very low'),
	(('Very small', 'Upper', 'Poor', 'on the outskirts'), 'Very low'),
	(('Very small', 'Upper', 'Average', 'in the center'), 'Favorable'),
	(('Very small', 'Upper', 'Average', 'near the center'), 'Low'),
	(('Very small', 'Upper', 'Average', 'far from the center'), 'Low'),
	(('Very small', 'Upper', 'Average', 'on the outskirts'), 'Very low'),
	(('Very small', 'Upper', 'Good', 'in the center'), 'Favorable'),
	(('Very small', 'Upper', 'Good', 'near the center'), 'Favorable'),
	(('Very small', 'Upper', 'Good', 'far from the center'), 'Low'),
	(('Very small', 'Upper', 'Good', 'on the outskirts'), 'Low'),
	(('Very small', 'Upper', 'Very good', 'in the center'), 'Average'),
	(('Very small', 'Upper', 'Very good', 'near the center'), 'Average'),
	(('Very small', 'Upper', 'Very good', 'far from the center'), 'Favorable'),
	(('Very small', 'Upper', 'Very good', 'on the outskirts'), 'Favorable'),
	(('Very small', 'Upper', 'Excellent', 'in the center'), 'High'),
	(('Very small', 'Upper', 'Excellent', 'near the center'), 'High'),
	(('Very small', 'Upper', 'Excellent', 'far from the center'), 'Average'),
	(('Very small', 'Upper', 'Excellent', 'on the outskirts'), 'Favorable'),
	(('Small', 'Lower', 'Very poor', 'in the center'), 'Very low'),
	(('Small', 'Lower', 'Very poor', 'near the center'), 'Very low'),
	(('Small', 'Lower', 'Very poor', 'far from the center'), 'Very low'),
	(('Small', 'Lower', 'Very poor', 'on the outskirts'), 'Very low'),
	(('Small', 'Lower', 'Poor', 'in the center'), 'Low'),
	(('Small', 'Lower', 'Poor', 'near the center'), 'Very low'),
	(('Small', 'Lower', 'Poor', 'far from the center'), 'Very low'),
	(('Small', 'Lower', 'Poor', 'on the outskirts'), 'Very low'),
	(('Small', 'Lower', 'Average', 'in the center'), 'Low'),
	(('Small', 'Lower', 'Average', 'near the center'), 'Low'),
	(('Small', 'Lower', 'Average', 'far from the center'), 'Low'),
	(('Small', 'Lower', 'Average', 'on the outskirts'), 'Very low'),
	(('Small', 'Lower', 'Good', 'in the center'), 'Favorable'),
	(('Small', 'Lower', 'Good', 'near the center'), 'Favorable'),
	(('Small', 'Lower', 'Good', 'far from the center'), 'Low'),
	(('Small', 'Lower', 'Good', 'on the outskirts'), 'Low'),
	(('Small', 'Lower', 'Very good', 'in the center'), 'Average'),
	(('Small', 'Lower', 'Very good', 'near the center'), 'Favorable'),
	(('Small', 'Lower', 'Very good', 'far from the center'), 'Favorable'),
	(('Small', 'Lower', 'Very good', 'on the outskirts'), 'Low'),
	(('Small', 'Lower', 'Excellent', 'in the center'), 'High'),
	(('Small', 'Lower', 'Excellent', 'near the center'), 'Average'),
	(('Small', 'Lower', 'Excellent', 'far from the center'), 'Average'),
	(('Small', 'Lower', 'Excellent', 'on the outskirts'), 'Favorable'),
	(('Small', 'Below middle', 'Very poor', 'in the center'), 'Very low'),
	(('Small', 'Below middle', 'Very poor', 'near the center'), 'Very low'),
	(('Small', 'Below middle', 'Very poor', 'far from the center'), 'Very low'),
	(('Small', 'Below middle', 'Very poor', 'on the outskirts'), 'Very low'),
	(('Small', 'Below middle', 'Poor', 'in the center'), 'Low'),
	(('Small', 'Below middle', 'Poor', 'near the center'), 'Low'),
	(('Small', 'Below middle', 'Poor', 'far from the center'), 'Very low'),
	(('Small', 'Below middle', 'Poor', 'on the outskirts'), 'Very low'),
	(('Small', 'Below middle', 'Average', 'in the center'), 'Favorable'),
	(('Small', 'Below middle', 'Average', 'near the center'), 'Low'),
	(('Small', 'Below middle', 'Average', 'far from the center'), 'Low'),
	(('Small', 'Below middle', 'Average', 'on the outskirts'), 'Very low'),
	(('Small', 'Below middle', 'Good', 'in the center'), 'Average'),
	(('Small', 'Below middle', 'Good', 'near the center'), 'Favorable'),
	(('Small', 'Below middle', 'Good', 'far from the center'), 'Low'),
	(('Small', 'Below middle', 'Good', 'on the outskirts'), 'Low'),
	(('Small', 'Below middle', 'Very good', 'in the center'), 'High'),
	(('Small', 'Below middle', 'Very good', 'near the center'), 'Average'),
	(('Small', 'Below middle', 'Very good', 'far from the center'), 'Favorable'),
	(('Small', 'Below middle', 'Very good', 'on the outskirts'), 'Favorable'),
	(('Small', 'Below middle', 'Excellent', 'in the center'), 'High'),
	(('Small', 'Below middle', 'Excellent', 'near the center'), 'High'),
	(('Small', 'Below middle', 'Excellent', 'far from the center'), 'Average'),
	(('Small', 'Below middle', 'Excellent', 'on the outskirts'), 'Average'),
	(('Small', 'Above middle', 'Very poor', 'in the center'), 'Low'),
	(('Small', 'Above middle', 'Very poor', 'near the center'), 'Very low'),
	(('Small', 'Above middle', 'Very poor', 'far from the center'), 'Very low'),
	(('Small', 'Above middle', 'Very poor', 'on the outskirts'), 'Very low'),
	(('Small', 'Above middle', 'Poor', 'in the center'), 'Low'),
	(('Small', 'Above middle', 'Poor', 'near the center'), 'Low'),
	(('Small', 'Above middle', 'Poor', 'far from the center'), 'Very low'),
	(('Small', 'Above middle', 'Poor', 'on the outskirts'), 'Very low'),
	(('Small', 'Above middle', 'Average', 'in the center'), 'Favorable'),
	(('Small', 'Above middle', 'Average', 'near the center'), 'Favorable'),
	(('Small', 'Above middle', 'Average', 'far from the center'), 'Low'),
	(('Small', 'Above middle', 'Average', 'on the outskirts'), 'Low'),
	(('Small', 'Above middle', 'Good', 'in the center'), 'Average'),
	(('Small', 'Above middle', 'Good', 'near the center'), 'Favorable'),
	(('Small', 'Above middle', 'Good', 'far from the center'), 'Favorable'),
	(('Small', 'Above middle', 'Good', 'on the outskirts'), 'Low'),
	(('Small', 'Above middle', 'Very good', 'in the center'), 'High'),
	(('Small', 'Above middle', 'Very good', 'near the center'), 'Average'),
	(('Small', 'Above middle', 'Very good', 'far from the center'), 'Average'),
	(('Small', 'Above middle', 'Very good', 'on the outskirts'), 'Favorable'),
	(('Small', 'Above middle', 'Excellent', 'in the center'), 'Very high'),
	(('Small', 'Above middle', 'Excellent', 'near the center'), 'High'),
	(('Small', 'Above middle', 'Excellent', 'far from the center'), 'High'),
	(('Small', 'Above middle', 'Excellent', 'on the outskirts'), 'Average'),
	(('Small', 'Upper', 'Very poor', 'in the center'), 'Low'),
	(('Small', 'Upper', 'Very poor', 'near the center'), 'Low'),
	(('Small', 'Upper', 'Very poor', 'far from the center'), 'Very low'),
	(('Small', 'Upper', 'Very poor', 'on the outskirts'), 'Very low'),
	(('Small', 'Upper', 'Poor', 'in the center'), 'Favorable'),
	(('Small', 'Upper', 'Poor', 'near the center'), 'Low'),
	(('Small', 'Upper', 'Poor', 'far from the center'), 'Low'),
	(('Small', 'Upper', 'Poor', 'on the outskirts'), 'Very low'),
	(('Small', 'Upper', 'Average', 'in the center'), 'Average'),
	(('Small', 'Upper', 'Average', 'near the center'), 'Favorable'),
	(('Small', 'Upper', 'Average', 'far from the center'), 'Low'),
	(('Small', 'Upper', 'Average', 'on the outskirts'), 'Low'),
	(('Small', 'Upper', 'Good', 'in the center'), 'Average'),
	(('Small', 'Upper', 'Good', 'near the center'), 'Average'),
	(('Small', 'Upper', 'Good', 'far from the center'), 'Favorable'),
	(('Small', 'Upper', 'Good', 'on the outskirts'), 'Favorable'),
	(('Small', 'Upper', 'Very good', 'in the center'), 'High'),
	(('Small', 'Upper', 'Very good', 'near the center'), 'High'),
	(('Small', 'Upper', 'Very good', 'far from the center'), 'Average'),
	(('Small', 'Upper', 'Very good', 'on the outskirts'), 'Favorable'),
	(('Small', 'Upper', 'Excellent', 'in the center'), 'Very high'),
	(('Small', 'Upper', 'Excellent', 'near the center'), 'Very high'),
	(('Small', 'Upper', 'Excellent', 'far from the center'), 'High'),
	(('Small', 'Upper', 'Excellent', 'on the outskirts'), 'Average'),
	(('Average', 'Lower', 'Very poor', 'in the center'), 'Low'),
	(('Average', 'Lower', 'Very poor', 'near the center'), 'Very low'),
	(('Average', 'Lower', 'Very poor', 'far from the center'), 'Very low'),
	(('Average', 'Lower', 'Very poor', 'on the outskirts'), 'Very low'),
	(('Average', 'Lower', 'Poor', 'in the center'), 'Favorable'),
	(('Average', 'Lower', 'Poor', 'near the center'), 'Low'),
	(('Average', 'Lower', 'Poor', 'far from the center'), 'Low'),
	(('Average', 'Lower', 'Poor', 'on the outskirts'), 'Very low'),
	(('Average', 'Lower', 'Average', 'in the center'), 'Favorable'),
	(('Average', 'Lower', 'Average', 'near the center'), 'Favorable'),
	(('Average', 'Lower', 'Average', 'far from the center'), 'Low'),
	(('Average', 'Lower', 'Average', 'on the outskirts'), 'Low'),
	(('Average', 'Lower', 'Good', 'in the center'), 'Average'),
	(('Average', 'Lower', 'Good', 'near the center'), 'Average'),
	(('Average', 'Lower', 'Good', 'far from the center'), 'Favorable'),
	(('Average', 'Lower', 'Good', 'on the outskirts'), 'Low'),
	(('Average', 'Lower', 'Very good', 'in the center'), 'High'),
	(('Average', 'Lower', 'Very good', 'near the center'), 'Average'),
	(('Average', 'Lower', 'Very good', 'far from the center'), 'Average'),
	(('Average', 'Lower', 'Very good', 'on the outskirts'), 'Favorable'),
	(('Average', 'Lower', 'Excellent', 'in the center'), 'Very high'),
	(('Average', 'Lower', 'Excellent', 'near the center'), 'High'),
	(('Average', 'Lower', 'Excellent', 'far from the center'), 'High'),
	(('Average', 'Lower', 'Excellent', 'on the outskirts'), 'Average'),
	(('Average', 'Below middle', 'Very poor', 'in the center'), 'Low'),
	(('Average', 'Below middle', 'Very poor', 'near the center'), 'Low'),
	(('Average', 'Below middle', 'Very poor', 'far from the center'), 'Very low'),
	(('Average', 'Below middle', 'Very poor', 'on the outskirts'), 'Very low'),
	(('Average', 'Below middle', 'Poor', 'in the center'), 'Favorable'),
	(('Average', 'Below middle', 'Poor', 'near the center'), 'Low'),
	(('Average', 'Below middle', 'Poor', 'far from the center'), 'Low'),
	(('Average', 'Below middle', 'Poor', 'on the outskirts'), 'Very low'),
	(('Average', 'Below middle', 'Average', 'in the center'), 'Average'),
	(('Average', 'Below middle', 'Average', 'near the center'), 'Favorable'),
	(('Average', 'Below middle', 'Average', 'far from the center'), 'Favorable'),
	(('Average', 'Below middle', 'Average', 'on the outskirts'), 'Low'),
	(('Average', 'Below middle', 'Good', 'in the center'), 'High'),
	(('Average', 'Below middle', 'Good', 'near the center'), 'Average'),
	(('Average', 'Below middle', 'Good', 'far from the center'), 'Favorable'),
	(('Average', 'Below middle', 'Good', 'on the outskirts'), 'Favorable'),
	(('Average', 'Below middle', 'Very good', 'in the center'), 'Very high'),
	(('Average', 'Below middle', 'Very good', 'near the center'), 'High'),
	(('Average', 'Below middle', 'Very good', 'far from the center'), 'Average'),
	(('Average', 'Below middle', 'Very good', 'on the outskirts'), 'Average'),
	(('Average', 'Below middle', 'Excellent', 'in the center'), 'Very high'),
	(('Average', 'Below middle', 'Excellent', 'near the center'), 'Very high'),
	(('Average', 'Below middle', 'Excellent', 'far from the center'), 'High'),
	(('Average', 'Below middle', 'Excellent', 'on the outskirts'), 'High'),
	(('Average', 'Above middle', 'Very poor', 'in the center'), 'Low'),
	(('Average', 'Above middle', 'Very poor', 'near the center'), 'Low'),
	(('Average', 'Above middle', 'Very poor', 'far from the center'), 'Low'),
	(('Average', 'Above middle', 'Very poor', 'on the outskirts'), 'Very low'),
	(('Average', 'Above middle', 'Poor', 'in the center'), 'Favorable'),
	(('Average', 'Above middle', 'Poor', 'near the center'), 'Favorable'),
	(('Average', 'Above middle', 'Poor', 'far from the center'), 'Low'),
	(('Average', 'Above middle', 'Poor', 'on the outskirts'), 'Low'),
	(('Average', 'Above middle', 'Average', 'in the center'), 'Average'),
	(('Average', 'Above middle', 'Average', 'near the center'), 'Average'),
	(('Average', 'Above middle', 'Average', 'far from the center'), 'Favorable'),
	(('Average', 'Above middle', 'Average', 'on the outskirts'), 'Low'),
	(('Average', 'Above middle', 'Good', 'in the center'), 'High'),
	(('Average', 'Above middle', 'Good', 'near the center'), 'Average'),
	(('Average', 'Above middle', 'Good', 'far from the center'), 'Average'),
	(('Average', 'Above middle', 'Good', 'on the outskirts'), 'Favorable'),
	(('Average', 'Above middle', 'Very good', 'in the center'), 'Very high'),
	(('Average', 'Above middle', 'Very good', 'near the center'), 'High'),
	(('Average', 'Above middle', 'Very good', 'far from the center'), 'High'),
	(('Average', 'Above middle', 'Very good', 'on the outskirts'), 'Average'),
	(('Average', 'Above middle', 'Excellent', 'in the center'), 'Very high'),
	(('Average', 'Above middle', 'Excellent', 'near the center'), 'Very high'),
	(('Average', 'Above middle', 'Excellent', 'far from the center'), 'Very high'),
	(('Average', 'Above middle', 'Excellent', 'on the outskirts'), 'High'),
	(('Average', 'Upper', 'Very poor', 'in the center'), 'Favorable'),
	(('Average', 'Upper', 'Very poor', 'near the center'), 'Low'),
	(('Average', 'Upper', 'Very poor', 'far from the center'), 'Low'),
	(('Average', 'Upper', 'Very poor', 'on the outskirts'), 'Very low'),
	(('Average', 'Upper', 'Poor', 'in the center'), 'Average'),
	(('Average', 'Upper', 'Poor', 'near the center'), 'Favorable'),
	(('Average', 'Upper', 'Poor', 'far from the center'), 'Favorable'),
	(('Average', 'Upper', 'Poor', 'on the outskirts'), 'Low'),
	(('Average', 'Upper', 'Average', 'in the center'), 'High'),
	(('Average', 'Upper', 'Average', 'near the center'), 'Average'),
	(('Average', 'Upper', 'Average', 'far from the center'), 'Favorable'),
	(('Average', 'Upper', 'Average', 'on the outskirts'), 'Favorable'),
	(('Average', 'Upper', 'Good', 'in the center'), 'High'),
	(('Average', 'Upper', 'Good', 'near the center'), 'High'),
	(('Average', 'Upper', 'Good', 'far from the center'), 'Average'),
	(('Average', 'Upper', 'Good', 'on the outskirts'), 'Average'),
	(('Average', 'Upper', 'Very good', 'in the center'), 'Very high'),
	(('Average', 'Upper', 'Very good', 'near the center'), 'Very high'),
	(('Average', 'Upper', 'Very good', 'far from the center'), 'High'),
	(('Average', 'Upper', 'Very good', 'on the outskirts'), 'Average'),
	(('Average', 'Upper', 'Excellent', 'in the center'), 'Extremely high'),
	(('Average', 'Upper', 'Excellent', 'near the center'), 'Very high'),
	(('Average', 'Upper', 'Excellent', 'far from the center'), 'Very high'),
	(('Average', 'Upper', 'Excellent', 'on the outskirts'), 'High'),
	(('Large', 'Lower', 'Very poor', 'in the center'), 'Favorable'),
	(('Large', 'Lower', 'Very poor', 'near the center'), 'Low'),
	(('Large', 'Lower', 'Very poor', 'far from the center'), 'Low'),
	(('Large', 'Lower', 'Very poor', 'on the outskirts'), 'Very low'),
	(('Large', 'Lower', 'Poor', 'in the center'), 'Favorable'),
	(('Large', 'Lower', 'Poor', 'near the center'), 'Favorable'),
	(('Large', 'Lower', 'Poor', 'far from the center'), 'Low'),
	(('Large', 'Lower', 'Poor', 'on the outskirts'), 'Low'),
	(('Large', 'Lower', 'Average', 'in the center'), 'Average'),
	(('Large', 'Lower', 'Average', 'near the center'), 'Average'),
	(('Large', 'Lower', 'Average', 'far from the center'), 'Favorable'),
	(('Large', 'Lower', 'Average', 'on the outskirts'), 'Favorable'),
	(('Large', 'Lower', 'Good', 'in the center'), 'High'),
	(('Large', 'Lower', 'Good', 'near the center'), 'High'),
	(('Large', 'Lower', 'Good', 'far from the center'), 'Average'),
	(('Large', 'Lower', 'Good', 'on the outskirts'), 'Favorable'),
	(('Large', 'Lower', 'Very good', 'in the center'), 'Very high'),
	(('Large', 'Lower', 'Very good', 'near the center'), 'High'),
	(('Large', 'Lower', 'Very good', 'far from the center'), 'High'),
	(('Large', 'Lower', 'Very good', 'on the outskirts'), 'Average'),
	(('Large', 'Lower', 'Excellent', 'in the center'), 'Extremely high'),
	(('Large', 'Lower', 'Excellent', 'near the center'), 'Very high'),
	(('Large', 'Lower', 'Excellent', 'far from the center'), 'Very high'),
	(('Large', 'Lower', 'Excellent', 'on the outskirts'), 'High'),
	(('Large', 'Below middle', 'Very poor', 'in the center'), 'Favorable'),
	(('Large', 'Below middle', 'Very poor', 'near the center'), 'Low'),
	(('Large', 'Below middle', 'Very poor', 'far from the center'), 'Low'),
	(('Large', 'Below middle', 'Very poor', 'on the outskirts'), 'Low'),
	(('Large', 'Below middle', 'Poor', 'in the center'), 'Average'),
	(('Large', 'Below middle', 'Poor', 'near the center'), 'Favorable'),
	(('Large', 'Below middle', 'Poor', 'far from the center'), 'Favorable'),
	(('Large', 'Below middle', 'Poor', 'on the outskirts'), 'Low'),
	(('Large', 'Below middle', 'Average', 'in the center'), 'High'),
	(('Large', 'Below middle', 'Average', 'near the center'), 'Average'),
	(('Large', 'Below middle', 'Average', 'far from the center'), 'Average'),
	(('Large', 'Below middle', 'Average', 'on the outskirts'), 'Favorable'),
	(('Large', 'Below middle', 'Good', 'in the center'), 'Very high'),
	(('Large', 'Below middle', 'Good', 'near the center'), 'High'),
	(('Large', 'Below middle', 'Good', 'far from the center'), 'Average'),
	(('Large', 'Below middle', 'Good', 'on the outskirts'), 'Average'),
	(('Large', 'Below middle', 'Very good', 'in the center'), 'Very high'),
	(('Large', 'Below middle', 'Very good', 'near the center'), 'Very high'),
	(('Large', 'Below middle', 'Very good', 'far from the center'), 'High'),
	(('Large', 'Below middle', 'Very good', 'on the outskirts'), 'High'),
	(('Large', 'Below middle', 'Excellent', 'in the center'), 'Extremely high'),
	(('Large', 'Below middle', 'Excellent', 'near the center'), 'Very high'),
	(('Large', 'Below middle', 'Excellent', 'far from the center'), 'Very high'),
	(('Large', 'Below middle', 'Excellent', 'on the outskirts'), 'Very high'),
	(('Large', 'Above middle', 'Very poor', 'in the center'), 'Favorable'),
	(('Large', 'Above middle', 'Very poor', 'near the center'), 'Favorable'),
	(('Large', 'Above middle', 'Very poor', 'far from the center'), 'Low'),
	(('Large', 'Above middle', 'Very poor', 'on the outskirts'), 'Low'),
	(('Large', 'Above middle', 'Poor', 'in the center'), 'Average'),
	(('Large', 'Above middle', 'Poor', 'near the center'), 'Average'),
	(('Large', 'Above middle', 'Poor', 'far from the center'), 'Favorable'),
	(('Large', 'Above middle', 'Poor', 'on the outskirts'), 'Low'),
	(('Large', 'Above middle', 'Average', 'in the center'), 'High'),
	(('Large', 'Above middle', 'Average', 'near the center'), 'High'),
	(('Large', 'Above middle', 'Average', 'far from the center'), 'Average'),
	(('Large', 'Above middle', 'Average', 'on the outskirts'), 'Favorable'),
	(('Large', 'Above middle', 'Good', 'in the center'), 'Very high'),
	(('Large', 'Above middle', 'Good', 'near the center'), 'High'),
	(('Large', 'Above middle', 'Good', 'far from the center'), 'High'),
	(('Large', 'Above middle', 'Good', 'on the outskirts'), 'Average'),
	(('Large', 'Above middle', 'Very good', 'in the center'), 'Extremely high'),
	(('Large', 'Above middle', 'Very good', 'near the center'), 'Very high'),
	(('Large', 'Above middle', 'Very good', 'far from the center'), 'Very high'),
	(('Large', 'Above middle', 'Very good', 'on the outskirts'), 'High'),
	(('Large', 'Above middle', 'Excellent', 'in the center'), 'Extremely high'),
	(('Large', 'Above middle', 'Excellent', 'near the center'), 'Extremely high'),
	(('Large', 'Above middle', 'Excellent', 'far from the center'), 'Very high'),
	(('Large', 'Above middle', 'Excellent', 'on the outskirts'), 'Very high'),
	(('Large', 'Upper', 'Very poor', 'in the center'), 'Average'),
	(('Large', 'Upper', 'Very poor', 'near the center'), 'Favorable'),
	(('Large', 'Upper', 'Very poor', 'far from the center'), 'Favorable'),
	(('Large', 'Upper', 'Very poor', 'on the outskirts'), 'Low'),
	(('Large', 'Upper', 'Poor', 'in the center'), 'High'),
	(('Large', 'Upper', 'Poor', 'near the center'), 'Average'),
	(('Large', 'Upper', 'Poor', 'far from the center'), 'Favorable'),
	(('Large', 'Upper', 'Poor', 'on the outskirts'), 'Favorable'),
	(('Large', 'Upper', 'Average', 'in the center'), 'Very high'),
	(('Large', 'Upper', 'Average', 'near the center'), 'High'),
	(('Large', 'Upper', 'Average', 'far from the center'), 'Average'),
	(('Large', 'Upper', 'Average', 'on the outskirts'), 'Average'),
	(('Large', 'Upper', 'Good', 'in the center'), 'Very high'),
	(('Large', 'Upper', 'Good', 'near the center'), 'Very high'),
	(('Large', 'Upper', 'Good', 'far from the center'), 'High'),
	(('Large', 'Upper', 'Good', 'on the outskirts'), 'High'),
	(('Large', 'Upper', 'Very good', 'in the center'), 'Extremely high'),
	(('Large', 'Upper', 'Very good', 'near the center'), 'Very high'),
	(('Large', 'Upper', 'Very good', 'far from the center'), 'Very high'),
	(('Large', 'Upper', 'Very good', 'on the outskirts'), 'High'),
	(('Large', 'Upper', 'Excellent', 'in the center'), 'Extremely high'),
	(('Large', 'Upper', 'Excellent', 'near the center'), 'Extremely high'),
	(('Large', 'Upper', 'Excellent', 'far from the center'), 'Extremely high'),
	(('Large', 'Upper', 'Excellent', 'on the outskirts'), 'Very high'),
	(('Very large', 'Lower', 'Very poor', 'in the center'), 'Average'),
	(('Very large', 'Lower', 'Very poor', 'near the center'), 'Favorable'),
	(('Very large', 'Lower', 'Very poor', 'far from the center'), 'Low'),
	(('Very large', 'Lower', 'Very poor', 'on the outskirts'), 'Low'),
	(('Very large', 'Lower', 'Poor', 'in the center'), 'Average'),
	(('Very large', 'Lower', 'Poor', 'near the center'), 'Average'),
	(('Very large', 'Lower', 'Poor', 'far from the center'), 'Favorable'),
	(('Very large', 'Lower', 'Poor', 'on the outskirts'), 'Favorable'),
	(('Very large', 'Lower', 'Average', 'in the center'), 'High'),
	(('Very large', 'Lower', 'Average', 'near the center'), 'High'),
	(('Very large', 'Lower', 'Average', 'far from the center'), 'Average'),
	(('Very large', 'Lower', 'Average', 'on the outskirts'), 'Average'),
	(('Very large', 'Lower', 'Good', 'in the center'), 'Very high'),
	(('Very large', 'Lower', 'Good', 'near the center'), 'Very high'),
	(('Very large', 'Lower', 'Good', 'far from the center'), 'High'),
	(('Very large', 'Lower', 'Good', 'on the outskirts'), 'Average'),
	(('Very large', 'Lower', 'Very good', 'in the center'), 'Extremely high'),
	(('Very large', 'Lower', 'Very good', 'near the center'), 'Very high'),
	(('Very large', 'Lower', 'Very good', 'far from the center'), 'Very high'),
	(('Very large', 'Lower', 'Very good', 'on the outskirts'), 'High'),
	(('Very large', 'Lower', 'Excellent', 'in the center'), 'Extremely high'),
	(('Very large', 'Lower', 'Excellent', 'near the center'), 'Extremely high'),
	(('Very large', 'Lower', 'Excellent', 'far from the center'), 'Very high'),
	(('Very large', 'Lower', 'Excellent', 'on the outskirts'), 'Very high'),
	(('Very large', 'Below middle', 'Very poor', 'in the center'), 'Average'),
	(('Very large', 'Below middle', 'Very poor', 'near the center'), 'Favorable'),
	(('Very large', 'Below middle', 'Very poor', 'far from the center'), 'Favorable'),
	(('Very large', 'Below middle', 'Very poor', 'on the outskirts'), 'Low'),
	(('Very large', 'Below middle', 'Poor', 'in the center'), 'High'),
	(('Very large', 'Below middle', 'Poor', 'near the center'), 'Average'),
	(('Very large', 'Below middle', 'Poor', 'far from the center'), 'Average'),
	(('Very large', 'Below middle', 'Poor', 'on the outskirts'), 'Favorable'),
	(('Very large', 'Below middle', 'Average', 'in the center'), 'Very high'),
	(('Very large', 'Below middle', 'Average', 'near the center'), 'High'),
	(('Very large', 'Below middle', 'Average', 'far from the center'), 'Average'),
	(('Very large', 'Below middle', 'Average', 'on the outskirts'), 'Average'),
	(('Very large', 'Below middle', 'Good', 'in the center'), 'Very high'),
	(('Very large', 'Below middle', 'Good', 'near the center'), 'Very high'),
	(('Very large', 'Below middle', 'Good', 'far from the center'), 'High'),
	(('Very large', 'Below middle', 'Good', 'on the outskirts'), 'High'),
	(('Very large', 'Below middle', 'Very good', 'in the center'), 'Extremely high'),
	(('Very large', 'Below middle', 'Very good', 'near the center'), 'Very high'),
	(('Very large', 'Below middle', 'Very good', 'far from the center'), 'Very high'),
	(('Very large', 'Below middle', 'Very good', 'on the outskirts'), 'Very high'),
	(('Very large', 'Below middle', 'Excellent', 'in the center'), 'Extremely high'),
	(('Very large', 'Below middle', 'Excellent', 'near the center'), 'Extremely high'),
	(('Very large', 'Below middle', 'Excellent', 'far from the center'), 'Extremely high'),
	(('Very large', 'Below middle', 'Excellent', 'on the outskirts'), 'Very high'),
	(('Very large', 'Above middle', 'Very poor', 'in the center'), 'Average'),
	(('Very large', 'Above middle', 'Very poor', 'near the center'), 'Average'),
	(('Very large', 'Above middle', 'Very poor', 'far from the center'), 'Favorable'),
	(('Very large', 'Above middle', 'Very poor', 'on the outskirts'), 'Favorable'),
	(('Very large', 'Above middle', 'Poor', 'in the center'), 'High'),
	(('Very large', 'Above middle', 'Poor', 'near the center'), 'High'),
	(('Very large', 'Above middle', 'Poor', 'far from the center'), 'Average'),
	(('Very large', 'Above middle', 'Poor', 'on the outskirts'), 'Favorable'),
	(('Very large', 'Above middle', 'Average', 'in the center'), 'Very high'),
	(('Very large', 'Above middle', 'Average', 'near the center'), 'Very high'),
	(('Very large', 'Above middle', 'Average', 'far from the center'), 'High'),
	(('Very large', 'Above middle', 'Average', 'on the outskirts'), 'Average'),
	(('Very large', 'Above middle', 'Good', 'in the center'), 'Extremely high'),
	(('Very large', 'Above middle', 'Good', 'near the center'), 'Very high'),
	(('Very large', 'Above middle', 'Good', 'far from the center'), 'Very high'),
	(('Very large', 'Above middle', 'Good', 'on the outskirts'), 'High'),
	(('Very large', 'Above middle', 'Very good', 'in the center'), 'Extremely high'),
	(('Very large', 'Above middle', 'Very good', 'near the center'), 'Extremely high'),
	(('Very large', 'Above middle', 'Very good', 'far from the center'), 'Very high'),
	(('Very large', 'Above middle', 'Very good', 'on the outskirts'), 'Very high'),
	(('Very large', 'Above middle', 'Excellent', 'in the center'), 'Extremely high'),
	(('Very large', 'Above middle', 'Excellent', 'near the center'), 'Extremely high'),
	(('Very large', 'Above middle', 'Excellent', 'far from the center'), 'Extremely high'),
	(('Very large', 'Above middle', 'Excellent', 'on the outskirts'), 'Extremely high'),
	(('Very large', 'Upper', 'Very poor', 'in the center'), 'High'),
	(('Very large', 'Upper', 'Very poor', 'near the center'), 'Average'),
	(('Very large', 'Upper', 'Very poor', 'far from the center'), 'Average'),
	(('Very large', 'Upper', 'Very poor', 'on the outskirts'), 'Favorable'),
	(('Very large', 'Upper', 'Poor', 'in the center'), 'Very high'),
	(('Very large', 'Upper', 'Poor', 'near the center'), 'High'),
	(('Very large', 'Upper', 'Poor', 'far from the center'), 'Average'),
	(('Very large', 'Upper', 'Poor', 'on the outskirts'), 'Average'),
	(('Very large', 'Upper', 'Average', 'in the center'), 'Very high'),
	(('Very large', 'Upper', 'Average', 'near the center'), 'Very high'),
	(('Very large', 'Upper', 'Average', 'far from the center'), 'High'),
	(('Very large', 'Upper', 'Average', 'on the outskirts'), 'High'),
	(('Very large', 'Upper', 'Good', 'in the center'), 'Extremely high'),
	(('Very large', 'Upper', 'Good', 'near the center'), 'Very high'),
	(('Very large', 'Upper', 'Good', 'far from the center'), 'Very high'),
	(('Very large', 'Upper', 'Good', 'on the outskirts'), 'Very high'),
	(('Very large', 'Upper', 'Very good', 'in the center'), 'Extremely high'),
	(('Very large', 'Upper', 'Very good', 'near the center'), 'Extremely high'),
	(('Very large', 'Upper', 'Very good', 'far from the center'), 'Extremely high'),
	(('Very large', 'Upper', 'Very good', 'on the outskirts'), 'Very high'),
	(('Very large', 'Upper', 'Excellent', 'in the center'), 'Extremely high'),
	(('Very large', 'Upper', 'Excellent', 'near the center'), 'Extremely high'),
	(('Very large', 'Upper', 'Excellent', 'far from the center'), 'Extremely high'),
	(('Very large', 'Upper', 'Excellent', 'on the outskirts'), 'Extremely high'),
	(('Extra large', 'Lower', 'Very poor', 'in the center'), 'High'),
	(('Extra large', 'Lower', 'Very poor', 'near the center'), 'Average'),
	(('Extra large', 'Lower', 'Very poor', 'far from the center'), 'Favorable'),
	(('Extra large', 'Lower', 'Very poor', 'on the outskirts'), 'Favorable'),
	(('Extra large', 'Lower', 'Poor', 'in the center'), 'High'),
	(('Extra large', 'Lower', 'Poor', 'near the center'), 'High'),
	(('Extra large', 'Lower', 'Poor', 'far from the center'), 'Average'),
	(('Extra large', 'Lower', 'Poor', 'on the outskirts'), 'Average'),
	(('Extra large', 'Lower', 'Average', 'in the center'), 'Very high'),
	(('Extra large', 'Lower', 'Average', 'near the center'), 'Very high'),
	(('Extra large', 'Lower', 'Average', 'far from the center'), 'High'),
	(('Extra large', 'Lower', 'Average', 'on the outskirts'), 'Average'),
	(('Extra large', 'Lower', 'Good', 'in the center'), 'Extremely high'),
	(('Extra large', 'Lower', 'Good', 'near the center'), 'Very high'),
	(('Extra large', 'Lower', 'Good', 'far from the center'), 'Very high'),
	(('Extra large', 'Lower', 'Good', 'on the outskirts'), 'High'),
	(('Extra large', 'Lower', 'Very good', 'in the center'), 'Extremely high'),
	(('Extra large', 'Lower', 'Very good', 'near the center'), 'Extremely high'),
	(('Extra large', 'Lower', 'Very good', 'far from the center'), 'Very high'),
	(('Extra large', 'Lower', 'Very good', 'on the outskirts'), 'Very high'),
	(('Extra large', 'Lower', 'Excellent', 'in the center'), 'Extremely high'),
	(('Extra large', 'Lower', 'Excellent', 'near the center'), 'Extremely high'),
	(('Extra large', 'Lower', 'Excellent', 'far from the center'), 'Extremely high'),
	(('Extra large', 'Lower', 'Excellent', 'on the outskirts'), 'Extremely high'),
	(('Extra large', 'Below middle', 'Very poor', 'in the center'), 'High'),
	(('Extra large', 'Below middle', 'Very poor', 'near the center'), 'Average'),
	(('Extra large', 'Below middle', 'Very poor', 'far from the center'), 'Average'),
	(('Extra large', 'Below middle', 'Very poor', 'on the outskirts'), 'Favorable'),
	(('Extra large', 'Below middle', 'Poor', 'in the center'), 'Very high'),
	(('Extra large', 'Below middle', 'Poor', 'near the center'), 'High'),
	(('Extra large', 'Below middle', 'Poor', 'far from the center'), 'High'),
	(('Extra large', 'Below middle', 'Poor', 'on the outskirts'), 'Average'),
	(('Extra large', 'Below middle', 'Average', 'in the center'), 'Very high'),
	(('Extra large', 'Below middle', 'Average', 'near the center'), 'Very high'),
	(('Extra large', 'Below middle', 'Average', 'far from the center'), 'High'),
	(('Extra large', 'Below middle', 'Average', 'on the outskirts'), 'High'),
	(('Extra large', 'Below middle', 'Good', 'in the center'), 'Extremely high'),
	(('Extra large', 'Below middle', 'Good', 'near the center'), 'Extremely high'),
	(('Extra large', 'Below middle', 'Good', 'far from the center'), 'Very high'),
	(('Extra large', 'Below middle', 'Good', 'on the outskirts'), 'Very high'),
	(('Extra large', 'Below middle', 'Very good', 'in the center'), 'Extremely high'),
	(('Extra large', 'Below middle', 'Very good', 'near the center'), 'Extremely high'),
	(('Extra large', 'Below middle', 'Very good', 'far from the center'), 'Extremely high'),
	(('Extra large', 'Below middle', 'Very good', 'on the outskirts'), 'Very high'),
	(('Extra large', 'Below middle', 'Excellent', 'in the center'), 'Extremely high'),
	(('Extra large', 'Below middle', 'Excellent', 'near the center'), 'Extremely high'),
	(('Extra large', 'Below middle', 'Excellent', 'far from the center'), 'Extremely high'),
	(('Extra large', 'Below middle', 'Excellent', 'on the outskirts'), 'Extremely high'),
	(('Extra large', 'Above middle', 'Very poor', 'in the center'), 'High'),
	(('Extra large', 'Above middle', 'Very poor', 'near the center'), 'High'),
	(('Extra large', 'Above middle', 'Very poor', 'far from the center'), 'Average'),
	(('Extra large', 'Above middle', 'Very poor', 'on the outskirts'), 'Average'),
	(('Extra large', 'Above middle', 'Poor', 'in the center'), 'Very high'),
	(('Extra large', 'Above middle', 'Poor', 'near the center'), 'Very high'),
	(('Extra large', 'Above middle', 'Poor', 'far from the center'), 'High'),
	(('Extra large', 'Above middle', 'Poor', 'on the outskirts'), 'Average'),
	(('Extra large', 'Above middle', 'Average', 'in the center'), 'Extremely high'),
	(('Extra large', 'Above middle', 'Average', 'near the center'), 'Very high'),
	(('Extra large', 'Above middle', 'Average', 'far from the center'), 'Very high'),
	(('Extra large', 'Above middle', 'Average', 'on the outskirts'), 'High'),
	(('Extra large', 'Above middle', 'Good', 'in the center'), 'Extremely high'),
	(('Extra large', 'Above middle', 'Good', 'near the center'), 'Extremely high'),
	(('Extra large', 'Above middle', 'Good', 'far from the center'), 'Very high'),
	(('Extra large', 'Above middle', 'Good', 'on the outskirts'), 'Very high'),
	(('Extra large', 'Above middle', 'Very good', 'in the center'), 'Extremely high'),
	(('Extra large', 'Above middle', 'Very good', 'near the center'), 'Extremely high'),
	(('Extra large', 'Above middle', 'Very good', 'far from the center'), 'Extremely high'),
	(('Extra large', 'Above middle', 'Very good', 'on the outskirts'), 'Extremely high'),
	(('Extra large', 'Above middle', 'Excellent', 'in the center'), 'Extremely high'),
	(('Extra large', 'Above middle', 'Excellent', 'near the center'), 'Extremely high'),
	(('Extra large', 'Above middle', 'Excellent', 'far from the center'), 'Extremely high'),
	(('Extra large', 'Above middle', 'Excellent', 'on the outskirts'), 'Extremely high'),
	(('Extra large', 'Upper', 'Very poor', 'in the center'), 'Very high'),
	(('Extra large', 'Upper', 'Very poor', 'near the center'), 'High'),
	(('Extra large', 'Upper', 'Very poor', 'far from the center'), 'High'),
	(('Extra large', 'Upper', 'Very poor', 'on the outskirts'), 'Average'),
	(('Extra large', 'Upper', 'Poor', 'in the center'), 'Very high'),
	(('Extra large', 'Upper', 'Poor', 'near the center'), 'Very high'),
	(('Extra large', 'Upper', 'Poor', 'far from the center'), 'High'),
	(('Extra large', 'Upper', 'Poor', 'on the outskirts'), 'High'),
	(('Extra large', 'Upper', 'Average', 'in the center'), 'Extremely high'),
	(('Extra large', 'Upper', 'Average', 'near the center'), 'Extremely high'),
	(('Extra large', 'Upper', 'Average', 'far from the center'), 'Very high'),
	(('Extra large', 'Upper', 'Average', 'on the outskirts'), 'Very high'),
	(('Extra large', 'Upper', 'Good', 'in the center'), 'Extremely high'),
	(('Extra large', 'Upper', 'Good', 'near the center'), 'Extremely high'),
	(('Extra large', 'Upper', 'Good', 'far from the center'), 'Extremely high'),
	(('Extra large', 'Upper', 'Good', 'on the outskirts'), 'Very high'),
	(('Extra large', 'Upper', 'Very good', 'in the center'), 'Extremely high'),
	(('Extra large', 'Upper', 'Very good', 'near the center'), 'Extremely high'),
	(('Extra large', 'Upper', 'Very good', 'far from the center'), 'Extremely high'),
	(('Extra large', 'Upper', 'Very good', 'on the outskirts'), 'Extremely high'),
	(('Extra large', 'Upper', 'Excellent', 'in the center'), 'Extremely high'),
	(('Extra large', 'Upper', 'Excellent', 'near the center'), 'Extremely high'),
	(('Extra large', 'Upper', 'Excellent', 'far from the center'), 'Extremely high'),
	(('Extra large', 'Upper', 'Excellent', 'on the outskirts'), 'Extremely high')
]
